const movies = [
	{
		_id: '1',
        nameRU: '33 слова о дизайне',
		nameEN: '33 words about design',
		country: 'Какая-то страна',
		director: 'Какой-то режиссёр',
		duration: '1ч42м',
		year: '2023',
		description: 'Описание фильма',
		image: '../images/movie.jpg',
	},
	{
		_id: '2',
        nameRU: '33 слова о дизайне',
		nameEN: '33 words about design',
		country: 'Какая-то страна',
		director: 'Какой-то режиссёр',
		duration: '1ч42м',
		year: '2023',
		description: 'Описание фильма',
		image: '../images/movie.jpg',
	},
	{
		_id: '3',
        nameRU: '33 слова о дизайне',
		nameEN: '33 words about design',
		country: 'Какая-то страна',
		director: 'Какой-то режиссёр',
		duration: '1ч42м',
		year: '2023',
		description: 'Описание фильма',
		image: '../images/movie.jpg',
	},
	{
		_id: '4',
        nameRU: '33 слова о дизайне',
		nameEN: '33 words about design',
		country: 'Какая-то страна',
		director: 'Какой-то режиссёр',
		duration: '1ч42м',
		year: '2023',
		description: 'Описание фильма',
		image: '../images/movie.jpg',
	},
    {
		_id: '5',
        nameRU: '33 слова о дизайне',
		nameEN: '33 words about design',
		country: 'Какая-то страна',
		director: 'Какой-то режиссёр',
		duration: '1ч42м',
		year: '2023',
		description: 'Описание фильма',
		image: '../images/movie.jpg',
	},
	{
		_id: '6',
        nameRU: '33 слова о дизайне',
		nameEN: '33 words about design',
		country: 'Какая-то страна',
		director: 'Какой-то режиссёр',
		duration: '1ч42м',
		year: '2023',
		description: 'Описание фильма',
		image: '../images/movie.jpg',
	},
]

export default movies;